export const MOVIES_LOADING = 'MOVIES_LOADING';
export const MOVIES_DATA = 'MOVIES_DATA';
export const MOVIES_ERROR = 'MOVIES_ERROR';

export const GET_MOVIE_ITEM_PEDING = 'GET_MOVIE_ITEM_PEDING';
export const GET_MOVIE_ITEM_RESOLVED = 'GET_MOVIE_ITEM_RESOLVED';
export const GET_MOVIE_ITEM_REJECTED = 'GET_MOVIE_ITEM_REJECTED';

export const GET_SESSION_ITEM_PEDING = 'GET_SESSION_ITEM_PEDING';
export const GET_SESSION_ITEM_RESOLVED = 'GET_SESSION_ITEM_RESOLVED';
export const GET_SESSION_ITEM_REJECTED = 'GET_SESSION_ITEM_REJECTED';


export const URL = 'http://subdomain.entony.fs.a-level.com.ua/api/';
export const URL_MOVIE = URL + 'movie';